feat:first version
eggjs/egg-view-vue pull request #4
Opened 2017-06-06 12:43 UTC by hubcarl

##### Checklist

- [x] `npm test` passes
- [x] tests and/or benchmarks are included
- [x] documentation is changed or added
- [ ] commit message follows commit guidelines

##### Affected core subsystem(s)

##### Description of change

- support vue 2.0+ jsbundle server side render
- support vue 2.3+ json bundle server sider render

2017-06-06 16:19 UTC, okoala commented on .travis.yml
> +  - '7'
加个 8 吧

2017-06-06 16:26 UTC, okoala commented on test/view-vue.test.js
> +      return request(app.callback())
可以用 `request(app.callback())` --> `app.httpRequest()`

2017-06-06 16:29 UTC, okoala commented on test/view-vue.test.js
> +          assert(res.text.indexOf('data-server-rendered="true"') > -1);
可以用 res.text.includes('data-server-rendered="true"')
下面一堆同理

2017-06-07 01:40 UTC, hubcarl commented on .travis.yml
> +  - '7'
好

2017-06-07 01:41 UTC, hubcarl commented on test/view-vue.test.js
> +      return request(app.callback())
ok，后面的测试用例用你这张方式试试

2017-06-07 01:47 UTC, atian25 commented on test/view-vue.test.js
> +          assert(res.text.indexOf('data-server-rendered="true"') > -1);
这里应该直接 `expect(/data-server-rendered="true"/)` 基于可以了吧，不用放到 callback 里面

2017-06-07 01:48 UTC, atian25 commented on .travis.yml
> +  - '7'
@hubcarl 不要手动改这里，修改 package.json 中的 `ci.version`，然后执行 `node node_modules/egg-ci/install.js`

2017-06-07 01:56 UTC, hubcarl commented on .travis.yml
> +  - '7'
好

2017-06-07 06:45 UTC, hubcarl commented
逻辑层面大家帮忙review一下，没问题就先发一个版本

2017-06-07 12:52 UTC, okoala commented
+1

2017-06-09 00:27 UTC, atian25 requested changes

2017-06-09 00:27 UTC, atian25 commented on README.md
> +     clientManifest: require('vue-ssr-client-manifest.json')
这个的路径不对吧?

2017-06-09 00:27 UTC, atian25 commented on README.md
> +  yield ctx.render('vue-ssr-server-bundle.json', { name: 'vue json render' });
render json?

2017-06-09 00:27 UTC, atian25 commented on config/config.default.js
> +   * renderOptions.template will override layout template
`@property {String} [renderOptions.template] - default layout template`

2017-06-09 00:27 UTC, atian25 commented on config/config.default.js
> +   * @property {Object} [cache] lru-cache options @see https://www.npmjs.com/package/lru-cache
开发期是不是要关闭这个 cache? 这样的话这个参数就可以是 `{Object|Boolean}`

2017-06-09 00:27 UTC, atian25 commented on lib/loader.js
> +    if (this.isCache) {
这里应该不需要判断这个了，直接 get 不到就 read 了

2017-06-09 00:27 UTC, atian25 commented on lib/engine.js
> +    this.fileLoader = new FileLoader(app, this.cache);
fileLoader 和 vue 共用一个 cache，会存在 key 相互覆盖的可能性吧？

2017-06-09 00:27 UTC, atian25 commented on lib/view.js
> +    return this.app.vue.renderBundle(bundle, { state: locals }, options);
为什么叫 state ?

2017-06-09 00:27 UTC, atian25 commented on lib/view.js
> +    const bundle = /\.json$/.test(name) ? require(name) : yield this.app.vue.readFile(name);
直接做到 readFile 里面去?

2017-06-09 00:27 UTC, atian25 commented on lib/view.js
> +  * render(name, locals, options = {}) {
`* render`, `renderString` 一个 generator 一个是 promise, 建议统一

2017-06-09 00:27 UTC, atian25 commented on lib/view.js
> +    this.app = ctx.app;
加个 `this.ctx = ctx`

2017-06-09 00:27 UTC, atian25 commented on package.json
> +    "vuex-router-sync": "^4.2.0",
这几个引入是为了?

2017-06-09 00:27 UTC, atian25 commented on package.json
> +    "axios": "^0.16.2",
还有这个

2017-06-09 00:27 UTC, atian25 commented on package.json
> +    "url": "https://github.com/eggjs/egg-view-vue/issues"
这个不要改，issue 只在主库开

2017-06-09 00:27 UTC, atian25 commented on test/fixtures/apps/view-vue-test/app/controller/view.js
> +exports.render23 = function* (ctx) {
取有意义的名词，如 `renderWithTemplate`

2017-06-09 00:27 UTC, atian25 commented on test/fixtures/apps/view-vue-test/app/controller/view.js
> +        name: 'swig render',
swig ?

2017-06-09 00:27 UTC, atian25 commented on test/fixtures/apps/view-vue-test/app/mocks/article/list.js
> +const data = {
简化下这个文件吧, 不用太多逻辑, 也不用中文

2017-06-12 08:38 UTC, atian25 commented
ping @hubcarl

2017-06-14 01:20 UTC, hubcarl commented on README.md
> +  yield ctx.render('vue-ssr-server-bundle.json', { name: 'vue json render' });
是的 vue2.3+ 官方支持render方式

2017-06-14 01:20 UTC, hubcarl commented on config/config.default.js
> +   * @property {Object} [cache] lru-cache options @see https://www.npmjs.com/package/lru-cache
可以是Boolean类型

2017-06-14 01:22 UTC, atian25 commented on config/config.default.js
> +   * @property {Object} [cache] lru-cache options @see https://www.npmjs.com/package/lru-cache
那要加下 jsdocs 说明，boolean 的话 `LRU(this.config.cache)` 支持？

2017-06-14 01:22 UTC, hubcarl commented on config/config.default.js
> +   * renderOptions.template will override layout template
这里的renderOptions 支持vue 全部的renderOptions ： https://ssr.vuejs.org/en/api.html#renderer-options

2017-06-14 01:27 UTC, atian25 commented on README.md
> +  yield ctx.render('vue-ssr-server-bundle.json', { name: 'vue json render' });
这个是在 app/view 根目录下么?

2017-06-14 01:27 UTC, atian25 commented on config/config.default.js
> +   * renderOptions.template will override layout template
这个知道，我这里提的是 jsdoc 格式

2017-06-14 01:29 UTC, hubcarl commented on lib/engine.js
> +    this.fileLoader = new FileLoader(app, this.cache);
这个不会， fileLoader 是以文件名作为换成的， vue 的createBundleRenderer是缓存文件内容的

2017-06-14 01:30 UTC, hubcarl commented on package.json
> +    "vuex-router-sync": "^4.2.0",
单元测试

2017-06-14 01:30 UTC, hubcarl commented on package.json
> +    "url": "https://github.com/eggjs/egg-view-vue/issues"
ok

2017-06-14 01:31 UTC, atian25 commented on lib/engine.js
> +    this.fileLoader = new FileLoader(app, this.cache);
两者的 key 还是有小概率冲突吧?

2017-06-14 01:32 UTC, hubcarl commented on test/fixtures/apps/view-vue-test/app/controller/view.js
> +exports.render23 = function* (ctx) {
ok

2017-06-14 01:33 UTC, hubcarl commented on test/fixtures/apps/view-vue-test/app/mocks/article/list.js
> +const data = {
ok

2017-06-14 01:33 UTC, hubcarl commented on test/fixtures/apps/view-vue-test/app/controller/view.js
> +        name: 'swig render',
这个需要改一下

2017-06-14 05:39 UTC, hubcarl commented on README.md
> +  yield ctx.render('vue-ssr-server-bundle.json', { name: 'vue json render' });
是的

2017-06-14 05:40 UTC, hubcarl commented on package.json
> +    "axios": "^0.16.2",
这个也是单元测试用的， 编译的JSBundle里面引用了axios

2017-06-14 06:48 UTC, atian25 approved these changes

2017-06-14 06:48 UTC, atian25 commented on config/config.default.js
> +   * use default LRU cache:
这里其实放在 README 就行了，先不管了，后面再修也行

2017-06-14 06:48 UTC, atian25 commented on lib/view.js
> +    return this.app.vue.renderBundle(name, { state: locals }, options);
state ?

2017-06-14 06:48 UTC, atian25 commented on test/fixtures/apps/view-vue-test/app/controller/view.js
> +  const url = ctx.url.replace(/\/app/, '') || '/';
这里其实可以用 `ctx.params.xx`

2017-06-14 07:37 UTC, atian25 approved these changes
先合并发个版本了，代码风格的后面再改

2017-06-14 07:38 UTC, atian25 commented
@okoala 你再看看

2017-06-14 07:53 UTC, okoala commented
@atian25  我OK，先合吧~

2017-06-14 07:53 UTC, merged

2017-06-14 09:03 UTC, atian25 commented
we made it! 1.0.0

2017-06-15 03:57 UTC, popomore commented
这里加个链接 https://eggjs.org/zh-cn/tutorials/index.html#模板引擎